apiVersion: v1
kind: Service
metadata:
  name: flask-camera-app-service
spec:
  selector:
    app: flask-camera-app
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer  # Use NodePort if you're running locally without a cloud provider